---
AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  KeyGiven:
    Fn::Not:
    - Fn::Equals:
      - Ref: KeyName
      - ''
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies: []
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: Role
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: Ami
      Tags:
      - Key: Name
        Value:
          Ref: Name
      InstanceType:
        Ref: InstanceType
      KeyName:
        Fn::If:
        - KeyGiven
        - Ref: KeyName
        - Ref: AWS::NoValue
      DisableApiTermination:
        Ref: TerminationProtection
      BlockDeviceMappings:
      - DeviceName: "/dev/xvda"
        Ebs:
          Encrypted: true
          KmsKeyId: alias/aws/ebs
          VolumeSize:
            Ref: RootVolumeSpace
          DeleteOnTermination: true
      IamInstanceProfile:
        Ref: InstanceProfile
      UserData:
        Fn::Base64:
          Fn::Sub: echo "Hello World!!"
      SecurityGroupIds:
      - Ref: InstanceSecurityGroup
      SubnetId:
        Ref: SubnetId
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VpcId
      GroupDescription: Ec2Server - ASG SG
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
Outputs:
  SecurityGroup:
    Value:
      Ref: InstanceSecurityGroup
  InstanceId:
    Value:
      Ref: Instance
  CfTemplateUrl:
    Value: "/simple-instance.compiled.yaml"
  CfTemplateVersion:
    Value: latest
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: ''
    NoEcho: false
    Description: VPC for network elements (SG)
  InstanceType:
    Type: String
    Default: t3.small
    NoEcho: false
    Description: Instance type, determining its hardware properties
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Default: ''
    NoEcho: false
    Description: 'Subnet Id for instance to run in '
  Ami:
    Type: String
    Default: ''
    NoEcho: false
    Description: Amazon Machine Image (AMI) id
  Name:
    Type: String
    Default: MyEc2Server
    NoEcho: false
    Description: Name tag for the instance
  TerminationProtection:
    Type: String
    Default: 'false'
    NoEcho: false
    Description: Allow instance termination by default
    AllowedValues:
    - 'false'
    - 'true'
  KeyName:
    Type: String
    Default: ''
    NoEcho: false
    Description: EC2 KeyPair, can be left blank
  RootVolumeSpace:
    Type: Number
    Default: '15'
    NoEcho: false
    Description: Size of the root volume, encrypted by default
Description: simple-instance@latest - vlatest
